// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: proto/flight.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      map[string]int32       `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_proto_flight_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_proto_flight_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClock) GetVersions() map[string]int32 {
	if x != nil {
		return x.Versions
	}
	return nil
}

type FlightState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Clock         *VectorClock           `protobuf:"bytes,2,opt,name=clock,proto3" json:"clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightState) Reset() {
	*x = FlightState{}
	mi := &file_proto_flight_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightState) ProtoMessage() {}

func (x *FlightState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightState.ProtoReflect.Descriptor instead.
func (*FlightState) Descriptor() ([]byte, []int) {
	return file_proto_flight_proto_rawDescGZIP(), []int{1}
}

func (x *FlightState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FlightState) GetClock() *VectorClock {
	if x != nil {
		return x.Clock
	}
	return nil
}

type GossipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlightId      string                 `protobuf:"bytes,1,opt,name=flight_id,json=flightId,proto3" json:"flight_id,omitempty"`
	State         *FlightState           `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_proto_flight_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_proto_flight_proto_rawDescGZIP(), []int{2}
}

func (x *GossipRequest) GetFlightId() string {
	if x != nil {
		return x.FlightId
	}
	return ""
}

func (x *GossipRequest) GetState() *FlightState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GossipRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

type GossipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_proto_flight_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flight_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_proto_flight_proto_rawDescGZIP(), []int{3}
}

func (x *GossipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_flight_proto protoreflect.FileDescriptor

const file_proto_flight_proto_rawDesc = "" +
	"\n" +
	"\x12proto/flight.proto\x12\x06flight\"\x89\x01\n" +
	"\vVectorClock\x12=\n" +
	"\bversions\x18\x01 \x03(\v2!.flight.VectorClock.VersionsEntryR\bversions\x1a;\n" +
	"\rVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"P\n" +
	"\vFlightState\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12)\n" +
	"\x05clock\x18\x02 \x01(\v2\x13.flight.VectorClockR\x05clock\"t\n" +
	"\rGossipRequest\x12\x1b\n" +
	"\tflight_id\x18\x01 \x01(\tR\bflightId\x12)\n" +
	"\x05state\x18\x02 \x01(\v2\x13.flight.FlightStateR\x05state\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\"*\n" +
	"\x0eGossipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2J\n" +
	"\x0fDataNodeService\x127\n" +
	"\x06Gossip\x12\x15.flight.GossipRequest\x1a\x16.flight.GossipResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_flight_proto_rawDescOnce sync.Once
	file_proto_flight_proto_rawDescData []byte
)

func file_proto_flight_proto_rawDescGZIP() []byte {
	file_proto_flight_proto_rawDescOnce.Do(func() {
		file_proto_flight_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_flight_proto_rawDesc), len(file_proto_flight_proto_rawDesc)))
	})
	return file_proto_flight_proto_rawDescData
}

var file_proto_flight_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_flight_proto_goTypes = []any{
	(*VectorClock)(nil),    // 0: flight.VectorClock
	(*FlightState)(nil),    // 1: flight.FlightState
	(*GossipRequest)(nil),  // 2: flight.GossipRequest
	(*GossipResponse)(nil), // 3: flight.GossipResponse
	nil,                    // 4: flight.VectorClock.VersionsEntry
}
var file_proto_flight_proto_depIdxs = []int32{
	4, // 0: flight.VectorClock.versions:type_name -> flight.VectorClock.VersionsEntry
	0, // 1: flight.FlightState.clock:type_name -> flight.VectorClock
	1, // 2: flight.GossipRequest.state:type_name -> flight.FlightState
	2, // 3: flight.DataNodeService.Gossip:input_type -> flight.GossipRequest
	3, // 4: flight.DataNodeService.Gossip:output_type -> flight.GossipResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_flight_proto_init() }
func file_proto_flight_proto_init() {
	if File_proto_flight_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_flight_proto_rawDesc), len(file_proto_flight_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_flight_proto_goTypes,
		DependencyIndexes: file_proto_flight_proto_depIdxs,
		MessageInfos:      file_proto_flight_proto_msgTypes,
	}.Build()
	File_proto_flight_proto = out.File
	file_proto_flight_proto_goTypes = nil
	file_proto_flight_proto_depIdxs = nil
}
